title: Welcome to EAT Blog
description: This is EAT Blog
author: EAT
github: https://github.com/dyeat
about: 在這部落格裡面紀錄一下,平常遇到用到的技術,方便日後回顧
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/logo.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

urls:
    - text: About Me
      url: /about/
    - text: Category
      url: /category/php



url: "https://dyeat.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
