title: Welcome to EAT Blog
description: 在這部落格裡面紀錄一下,平常遇到用到的技術,方便日後回顧
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/dyeat" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: EAT
  image: '/static/img/logo.png'
  job: 
  bio:
  email: 


# Google Analytics
google-analytics: UA-141503372-1


# Collestions
collections:
  projects:
    output: false


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap


sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock